apiVersion: v1
kind: Secret
metadata:
  name: auth-db
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "auth-db.ct6a8cwoqfzj.us-east-2.rds.amazonaws.com"
  DB_USER: "svcPostgresAdmin"
  DB_PASS: "AdminPostgres2026"
  MASTER_KEY: "admin-secreto-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-db
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "flag-db.ct6a8cwoqfzj.us-east-2.rds.amazonaws.com"
  DB_USER: "svcPostgresAdmin"
  DB_PASS: "AdminPostgres2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-db
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "targeting-db.ct6a8cwoqfzj.us-east-2.rds.amazonaws.com"
  DB_USER: "svcPostgresAdmin"
  DB_PASS: "AdminPostgres2026"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-cache
  namespace: togglemaster
type: Opaque
stringData:
  REDIS_HOST: "master.evaluation-cache.a28fcb.use2.cache.amazonaws.com"
  REDIS_PORT: "6379"