apiVersion: v1
kind: Secret
metadata:
  name: auth-db
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "VALORNOCLUSTER"
  DB_USER: "VALORNOCLUSTER"
  DB_PASS: "VALORNOCLUSTER"
  MASTER_KEY: "admin-secreto-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-db
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "VALORNOCLUSTER"
  DB_USER: "VALORNOCLUSTER"
  DB_PASS: "VALORNOCLUSTER"
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-db
  namespace: togglemaster
type: Opaque
stringData:
  DB_HOST: "VALORNOCLUSTER"
  DB_USER: "VALORNOCLUSTER"
  DB_PASS: "VALORNOCLUSTER"
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-cache
  namespace: togglemaster
type: Opaque
stringData:
  REDIS_HOST: "VALORNOCLUSTER"
  REDIS_PORT: "6379"
