apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SERVICE_PORT: "3000"
  AUTH_SERVICE_URL: "http://auth"
  FLAG_SERVICE_URL: "http://flag"
  TARGETING_SERVICE_URL: "http://targeting"
