apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
  labels:
    app: targeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
      - name: targeting-service
        image: 236604670467.dkr.ecr.us-east-2.amazonaws.com/targeting-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8003
          name: http
        
        env:
        # --- Vari√°veis Base ---
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: targeting-db
              key: DB_HOST     
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: targeting-db
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: targeting-db
              key: DB_PASS
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "targeting_db"

        - name: DATABASE_URL
          value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=require"
        
        - name: AUTH_SERVICE_URL
          value: "http://auth-service"

        # Recursos
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "600m"   
            memory: "512Mi"

        # Probes
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 20
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: togglemaster
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
  - port: 80
    targetPort: 8003
    protocol: TCP
    name: http